from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

CONFIG = {
    "camera_id": 0,
    "frame_width": 1280,
    "frame_height": 720,
    "target_fps": 20,
    "live_yaw_threshold": 45.0,
    "live_pitch_down_threshold": -35.0,
    "live_distraction_duration": 1.0,
    "video_detection_scale": 2.2,
    "video_face_min_detection_confidence": 0.35,
    "video_face_min_tracking_confidence": 0.35,
    "video_yaw_threshold": 50.0,
    "video_distraction_duration": 0.8,
    "video_ear_threshold": 0.035,
    "video_sleep_duration": 3.5,
    "video_mar_threshold": 0.58,
    "video_talk_duration": 0.8,
    "video_progressive_drowsiness_ear_threshold": 0.035,
    "video_use_pitch_distraction": False,
    "phone_detection_enabled": True,
    "phone_model_path": "yolov8n.pt",
    "phone_confidence": 0.08,
    "phone_min_aspect_ratio": 1.2,
    "phone_max_aspect_ratio": 4.8,
    "phone_owner_max_relative_y": 0.76,
    "phone_owner_min_width_ratio": 0.12,
    "phone_owner_min_height_ratio": 0.04,
    "person_confidence": 0.22,
    "phone_interval_frames": 3,
    "phone_near_student_scale": 1.8,
    "video_phone_duration": 0.18,
    "video_phone_hold_seconds": 1.8,
    "video_phone_context_seconds": 3.0,
    "video_peer_distraction_enabled": True,
    "video_peer_yaw_threshold": 38.0,
    "video_peer_distraction_duration": 0.35,
    "video_peer_body_only_enabled": False,
    "video_peer_body_distance_ratio": 0.4,
    "person_tracking_enabled": True,
    "person_tracker_backend": "yolo",
    "person_min_box_area_ratio": 0.004,
    "person_memory_seconds": 6.0,
    "person_new_track_grace_seconds": 2.0,
    "person_phone_near_scale": 1.15,

    "yaw_threshold": 30.0,
    "pitch_down_threshold": -25.0,
    "ear_threshold": 0.22,
    "sleep_duration": 3.0,
    "mar_threshold": 0.60,
    "talk_duration": 2.0,
    "absent_duration": 3.0,

    "attention_alpha": 0.15,
    "attention_rates": {
        "OK": 1.0,
        "DISTRACTED": -2.0,
        "TALKING": -3.0,
        "SLEEPING": -5.0,
        "ABSENT": -6.0,
        "PHONE_USAGE": -4.0,
        "BODY_ONLY": 0.0,
    },

    "buffer_seconds": 60.0,
    "pattern_interval": 0.5,
    "frequent_distraction_window": 30.0,
    "frequent_distraction_seconds": 3.0,
    "sustained_distraction_seconds": 5.0,
    "rapid_attention_drop_window": 20.0,
    "rapid_attention_drop_points": 30.0,

    "liveness_threshold": 0.35,
    "liveness_warmup_seconds": 4.0,
    "liveness_window_seconds": 8.0,

    "identity_similarity_threshold": 0.88,
    "identity_check_interval": 0.5,

    "database_csv": PROJECT_ROOT / "database" / "students.csv",
    "evidence_dir": PROJECT_ROOT / "evidence",
    "evidence_images_dir": PROJECT_ROOT / "evidence" / "images",
    "violations_csv": PROJECT_ROOT / "evidence" / "violations.csv",
}
